### ISSUE TITLE
Create RPCs for Fetching Dynamic Pool Info

### ISSUE THREAD

**Issue by distributedstatemachine** [RaoFoundation/subtensor#350]
## Description 
The python package currently makes [4 queries to subtensor](https://github.com/opentensor/bittensor/blob/dynamic/bittensor/subtensor.py#L3367-L3386) in order to retrieve the dynamic pool info, which leads to a higher latency. 

This PR is reduce of the process , but implementing APIs of subtensor that return this information. 

## Acceptance Criteria 

- [ ] The python package should be able to retrieve dynamic pool info for a single pool given a netuid.
- [ ]  The python package should be able to retrieve the dynamic pool info for all the pools

## Tasks

- [x] Implement `dynamic_pool_info`: Returns the pool info for a single pool given the netuid
- [x] Implement `dynamic_pool_infos`: Returns dynamic pool info for all the pools.
- [ ] Update python package

**Comment by distributedstatemachine** [comment]
Closed at Stale
