### ISSUE TITLE
Fix Free Transactions

### ISSUE THREAD

**Issue by distributedstatemachine** [RaoFoundation/subtensor#403]
## Description

Currently, our runtime does not properly handle fee-free transactions using the [pallet_skip_feeless_payment](https://docs.rs/pallet-skip-feeless-payment/latest/pallet_skip_feeless_payment/) module. This leads to inconsistencies and potential issues with transaction processing, as free transactions now require a fee.. The recent upgrade to Polkadot v1.10 removed the previous functionality, causing a regression in our system. In essence , `Pays=No` becomes a noop. 

## Acceptance Criteria

- Integrate the [pallet_skip_feeless_payment](file:///Users/samueldare/code/samtvlabs/bittensor/subtensor#913%2C43-913%2C43) module into the runtime.
- Define the necessary associated types and implement the required traits for the `SkipFeelessPaymentConfig`.
- Update the [RuntimeEvent](file:///Users/samueldare/code/samtvlabs/bittensor/subtensor#995%2C34-995%2C34) enum to include the [SkipFeelessPayment](file:///Users/samueldare/code/samtvlabs/bittensor/subtensor#1002%2C54-1002%2C54) variant.
- Ensure that fee-free transactions, including the faucet functionality, are correctly identified and processed.

## Tasks

- [ ] Update the runtime's [Cargo.toml](file:///Users/samueldare/code/samtvlabs/bittensor/subtensor/Cargo.toml#1%2C1-1%2C1) file to include the `pallet-skip-feeless-payment` dependency.
- [ ] Implement the `pallet_skip_feeless_payment::Config` trait for the runtime:
  ```rust
  impl pallet_skip_feeless_payment::Config for Runtime {
      type RuntimeEvent = RuntimeEvent;

      fn is_fee_free(call: &Self::RuntimeCall) -> bool {
          // Add logic to determine if a call is fee-free
          // ...
      }
  }
  ```
- [ ] Update the `RuntimeEvent` enum in `runtime/src/lib.rs`:
  ```rust
  #[derive(Debug, Encode, Decode, PartialEq, Eq, Clone)]
  #[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
  pub enum RuntimeEvent {
      // ...
      SkipFeelessPayment(pallet_skip_feeless_payment::Event<Runtime>),
      // ...
  }
  ```
- [ ] Update the `construct_runtime!` macro to include the `SkipFeelessPayment` module.
- [ ] Test the changes to ensure fee-free transactions, including the faucet, are correctly processed.

## Related Links

- https://docs.rs/pallet-skip-feeless-payment/latest/pallet_skip_feeless_payment/
- https://github.com/paritytech/polkadot-sdk/issues/1725
- https://discord.com/channels/799672011265015819/1237848735195598979

**Comment by open-junius** [comment]
According to my investigation, the root cause is the `account.providers.is_zero() && account.sufficients.is_zero()` check added when nonce check in extrinsic extension. We can't fix in via introduce the feeless trait for some extrinsic. Feeless is the machenism in transaction payment pallet, to check accept the transaction or not. But the added check happens before it, the extrinsic fails when check extrinsic extension.

**Comment by open-junius** [comment]
https://github.com/paritytech/polkadot-sdk/pull/4165/files fix from upstream. which can fix it but we need wait for its merge

**Comment by distributedstatemachine** [comment]
Closed by https://github.com/opentensor/subtensor/pull/404
