### ISSUE TITLE
Return Hotkey Stake

### ISSUE THREAD

**Issue by distributedstatemachine** [RaoFoundation/subtensor#601]
## Description

Cortex currently has to manually iterate the delegate map to return nominators stake. This makes the extension slow , as it takes about 30s to render this. In order to reduce the load  on the extension, we need to implement a new RPC method `get_hotkey_stake_info` that takes a hotkey as input and returns the total stake of the hotkey and its stake distribution across delegates. This information is crucial for users to understand their staking positions and for applications to display accurate staking data.

The RPC should return the data as a `Vec<u8>` to maintain consistency with existing RPCs and allow for efficient data transfer.

## Acceptance Criteria

- Implement a new `get_hotkey_stake_info` method in the `stake_info.rs` file.
- The method should return a `HotkeyStakeInfo` struct containing:
  - The total stake for the given hotkey.
  - A list of delegates with the hotkey's stake on each delegate.
- Update the runtime API to include the new `get_hotkey_stake_info` method.
- Implement the RPC handler in the node's RPC module, ensuring it returns a `Vec<u8>`.
- Ensure the RPC can be called via the Polkadot.js API and returns decodable data.
- Add appropriate error handling for invalid inputs or other potential issues.
- Write unit tests to verify the correctness of the new method.
- Update documentation to reflect the new RPC method.

## Tasks

- [ ] Implement `get_hotkey_stake_info` method in `stake_info.rs`

```rust
#[derive(Encode, Decode, TypeInfo)]
pub struct HotkeyDelegateInfo<T: Config> {
    pub delegate: T::AccountId,
    pub stake: u64,
}

#[derive(Encode, Decode, TypeInfo)]
pub struct HotkeyStakeInfo<T: Config> {
    pub total_stake: u64,
    pub delegate_info: Vec<HotkeyDelegateInfo<T>>,
}

impl<T: Config> Pallet<T> {
    pub fn get_hotkey_stake_info(hotkey: T::AccountId) -> HotkeyStakeInfo<T> {
        let mut total_stake = 0u64;
        let mut delegate_info = Vec::new();

        for (delegate, _) in Delegates::<T>::iter() {
            if let Some(stake) = Stake::<T>::get(hotkey.clone(), delegate.clone()) {
                if stake > 0 {
                    total_stake += stake;
                    delegate_info.push(HotkeyDelegateInfo {
                        delegate: delegate.clone(),
                        stake,
                    });
                }
            }
        }

        HotkeyStakeInfo {
            total_stake,
            delegate_info,
        }
    }
}
```

- [ ] Update runtime API definition in `runtime/src/lib.rs`

```rust
sp_api::decl_runtime_apis! {
    pub trait StakeInfoRuntimeApi {
        fn get_hotkey_stake_info(hotkey: AccountId) -> Vec<u8>;
    }
}
```

- [ ] Update pallet implementation in `pallets/subtensor/src/lib.rs`

```rust
impl<T: Config> Pallet<T> {
    pub fn get_hotkey_stake_info(hotkey: T::AccountId) -> Vec<u8> {
        let stake_info = Self::get_hotkey_stake_info(hotkey);
        stake_info.encode()
    }
}
```

- [ ] Implement RPC handler
```rust
impl<C, M> SubtensorApiServer for SubtensorApi<C, M>
where
    C: Send + Sync + 'static,
    C: ProvideRuntimeApi<Block>,
    C::Api: SubtensorRuntimeApi<Block, AccountId>,
    M: Send + Sync + 'static,
{
    fn get_hotkey_stake_info(&self, hotkey: AccountId) -> Result<Vec<u8>> {
        let api = self.client.runtime_api();
        let at = BlockId::hash(self.client.info().best_hash);
        api.get_hotkey_stake_info(&at, hotkey).map_err(|e| RpcError {
            code: ErrorCode::ServerError(9876),
            message: "Unable to get hotkey stake info".into(),
            data: Some(format!("{:?}", e).into()),
        })
    }
}
```

- [ ] Write unit tests for the new method

- [ ] Update documentation
